version: '3'

services:
#  mysql-db:

#  redis-cache:

#  authentication-service:

#  data-service:

#  search-suggestion-service:

#  payment-service:

  react-ui:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: react-service-container
    stdin_open: true
    restart: always
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    environment:
      - REACT_APP_STRIPE_PUBLISH_KEY=${REACT_APP_STRIPE_PUBLISH_KEY}
      - REACT_APP_GOOGLE_AUTH_CLIENT_ID=${REACT_APP_GOOGLE_AUTH_CLIENT_ID}
      - REACT_APP_COMMON_DATA_SERVICE_PORT=${COMMON_DATA_SERVICE_PORT}
      - REACT_APP_AUTHENTICATION_SERVICE_PORT=${AUTHENTICATION_SERVICE_PORT}
      - REACT_APP_PAYMENT_SERVICE_PORT=${PAYMENT_SERVICE_PORT}
      - REACT_APP_SEARCH_SUGGESTION_SERVICE_PORT=${SEARCH_SUGGESTION_SERVICE_PORT}
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
#    depends_on:
#      - mysql-db
#      - redis-cache
#      - authentication-service
#      - common-data-service
#      - search-suggestion-service
#      - payment-service
    networks:
      - spring-microservices
networks:
  spring-microservices:
    external: true
